# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-Tag-Amazon
version:      0.33
version_from: lib/Music/Tag/Amazon.pm
installdirs:  site
requires:
    Cache::Cache:                  1.05
    Data::Dumper:                  2
    Digest::SHA1:                  2.11
    File::Copy:                    0
    LWP:                           5.805
    Music::Tag:                    0.33
    Net::Amazon:                   0.55
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
