--- #YAML:1.0
name:                Music-Tag-Amazon
version:             0.29
abstract:            Plugin module for Music::Tag to get information from Amazon.com
license:             perl
author:              
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::Cache:                  1.05
    Data::Dumper:                  2
    Digest::SHA1:                  2.11
    File::Copy:                    0
    LWP:                           5.805
    Music::Tag:                    0.27
    Net::Amazon:                   0.43
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
